resources:
- name: app_sources
  type: git
  source:
    uri: https://github.com/balajigan/PCF-HelloWorld.git
- name: dev_deployment
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: username
    password: pwd
    organization: BalajiDemo
    space: development
    skip_cert_check: true

jobs:
- name: build
  plan:
  - get: app_sources
    trigger: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}
      inputs:
        - name: app_sources
      outputs:
        - name: mvn-package-output
      run:
        path: bash
        args: 
        - -exc
        - |
          set -e -u -x
          cd app_sources/
          echo $PWD
          mvn clean package
          cp target/PCF-HelloWorld-1.0.0.jar mvn-package-output/.
- name: deploy-to-PCF
  serial: true
  plan:
  - get: app_sources
    trigger: true	
  - put: dev_deployment
    params:
      manifest: app_sources/manifest.yml
